secrets:
- AIRTABLE_API_KEY
- AIRTABLE_BASE_ID
- AIRTABLE_TREES_TABLE_NAME
- AIRTABLE_SPECIES_TABLE_NAME
- AIRTABLE_SUPERVISORS_TABLE_NAME
- AIRTABLE_SITES_TABLE_NAME
- CLOUDINARY_CLOUD_NAME
- CLOUDINARY_UPLOAD_PRESET_NAME
- TEST_AIRTABLE_API_KEY
- TEST_AIRTABLE_BASE_ID
- TEST_AIRTABLE_TABLE_NAME_PREFIX
- PROTECT_EARTH_API_TOKEN
- PROTECT_EARTH_API_BASE_URL
- PROTECT_EARTH_ENV_NAME
- ROLLBAR_AUTH_TOKEN
outputs:
- ./Tree Tracker/Secrets.swift