secrets:
- CLOUDINARY_CLOUD_NAME
- CLOUDINARY_UPLOAD_PRESET_NAME
- AWS_BUCKET_NAME
- AWS_ACCESS_KEY
- AWS_SECRET_KEY
- PROTECT_EARTH_API_TOKEN
- PROTECT_EARTH_API_BASE_URL
- PROTECT_EARTH_ENV_NAME
- ROLLBAR_AUTH_TOKEN
outputs:
- ./Tree Tracker/Secrets.swift